
/**
 * Auto-generated by cache-keys-plugin.ts
 * DO NOT EDIT MANUALLY
 */

/**
 * Union type of all GraphQL object types that don't have an id field.
 * This is used to ensure that the cacheKeys object in UrqlCacheKeys.ts
 * includes all types without an id and doesn't include types with an id.
 */
export type TypesWithNoId = 'ArtistAppearsOn' | 'ArtistAppearsOnRelease' | 'ArtistConnectedExternalService' | 'ArtistImages' | 'ArtistImportBackgroundJob' | 'ArtistImportBackgroundProgress' | 'ArtistImportBackgroundQueueState' | 'ArtistImportHistoryItem' | 'ArtistImportSearchRoot' | 'ArtistSearchRoot' | 'ArtistTopTrack' | 'CacheStatistics' | 'ClientPlaybackCommand' | 'ClientPlaybackState' | 'ConnectivityStatus' | 'DownloadHistoryItem' | 'DownloadsSearchRoot' | 'ExternalServicesSearchRoot' | 'FileSystemSearchRoot' | 'ImportPlaylistSearchRoot' | 'ImportedRelease' | 'JsonRelease' | 'JsonTrack' | 'JsonTrackCredit' | 'JsonTrackServiceConnections' | 'JsonTrackStatistics' | 'KeyValuePairOfInt32AndDownloadProgress' | 'LastFmStatistics' | 'LastFmTag' | 'LibraryCacheTrackStatus' | 'LibraryReleaseDownloadStatusUpdate' | 'ListenBrainzQueryRoot' | 'MbAlbumImages' | 'MbArtistImages' | 'MbLabelInfo' | 'MbMedium' | 'MbNameCredit' | 'MbRelation' | 'MusicBrainzArtistSearchRoot' | 'MusicBrainzRecordingSearchRoot' | 'MusicBrainzReleaseGroupSearchRoot' | 'MusicBrainzReleaseSearchRoot' | 'MusicBrainzSearchRoot' | 'OnlineClient' | 'PageInfo' | 'PlaylistSearchRoot' | 'RecommendationsSearchRoot' | 'ReleaseServiceConnections' | 'ScoredRelease' | 'ServerLibrarySearchRoot' | 'SharingStatistics' | 'SimilarArtist' | 'SlotProgressUpdate' | 'SlotStatusUpdate' | 'SpotifyArtistSearchRoot' | 'SpotifyImage' | 'SpotifyPlaylistSearchRoot' | 'StorageStats' | 'TrackCredit' | 'TrackStatistics' | 'UserSearchRoot' | 'UsersConnection' | 'UsersEdge';

/**
 * Union type of all GraphQL object types that have an id field.
 * This is used for reference and validation.
 */
export type TypesWithId = 'Artist' | 'ArtistImportProgress' | 'ArtistImportQueueItem' | 'ArtistImportQueueState' | 'ArtistImportStatusInfo' | 'DownloadProgress' | 'DownloadQueueItem' | 'DownloadQueueState' | 'DownloadSlotInfo' | 'ExternalArtist' | 'ExternalRoot' | 'ExternalService' | 'FileSystemEntry' | 'JsonLabelInfo' | 'LastFmAlbum' | 'LastFmArtist' | 'LastFmTrack' | 'LikedSong' | 'ListenBrainzUserInfo' | 'MbArtist' | 'MbGenre' | 'MbLabel' | 'MbRecording' | 'MbRecordingStreamingServiceInfo' | 'MbRelease' | 'MbReleaseGroup' | 'MbTrack' | 'Ping' | 'Playlist' | 'PlaylistItem' | 'Release' | 'ServerLibraryManifestStatus' | 'ServerSettings' | 'SoulSeekRoot' | 'SoulSeekStatus' | 'SpotifyArtist' | 'SpotifyPlaylist' | 'SpotifyTrack' | 'Track' | 'TrackMedia' | 'Url' | 'User';

/**
 * Type guard to check if a type has an id field.
 * @param type The type to check
 * @returns True if the type has an id field, false otherwise
 */
export function hasIdField(type: string): type is TypesWithId {
  const typesWithId: string[] = ['Artist', 'ArtistImportProgress', 'ArtistImportQueueItem', 'ArtistImportQueueState', 'ArtistImportStatusInfo', 'DownloadProgress', 'DownloadQueueItem', 'DownloadQueueState', 'DownloadSlotInfo', 'ExternalArtist', 'ExternalRoot', 'ExternalService', 'FileSystemEntry', 'JsonLabelInfo', 'LastFmAlbum', 'LastFmArtist', 'LastFmTrack', 'LikedSong', 'ListenBrainzUserInfo', 'MbArtist', 'MbGenre', 'MbLabel', 'MbRecording', 'MbRecordingStreamingServiceInfo', 'MbRelease', 'MbReleaseGroup', 'MbTrack', 'Ping', 'Playlist', 'PlaylistItem', 'Release', 'ServerLibraryManifestStatus', 'ServerSettings', 'SoulSeekRoot', 'SoulSeekStatus', 'SpotifyArtist', 'SpotifyPlaylist', 'SpotifyTrack', 'Track', 'TrackMedia', 'Url', 'User'];
  return typesWithId.includes(type);
}

/**
 * Type guard to check if a type doesn't have an id field.
 * @param type The type to check
 * @returns True if the type doesn't have an id field, false otherwise
 */
export function hasNoIdField(type: string): type is TypesWithNoId {
  const typesWithNoId: string[] = ['ArtistAppearsOn', 'ArtistAppearsOnRelease', 'ArtistConnectedExternalService', 'ArtistImages', 'ArtistImportBackgroundJob', 'ArtistImportBackgroundProgress', 'ArtistImportBackgroundQueueState', 'ArtistImportHistoryItem', 'ArtistImportSearchRoot', 'ArtistSearchRoot', 'ArtistTopTrack', 'CacheStatistics', 'ClientPlaybackCommand', 'ClientPlaybackState', 'ConnectivityStatus', 'DownloadHistoryItem', 'DownloadsSearchRoot', 'ExternalServicesSearchRoot', 'FileSystemSearchRoot', 'ImportPlaylistSearchRoot', 'ImportedRelease', 'JsonRelease', 'JsonTrack', 'JsonTrackCredit', 'JsonTrackServiceConnections', 'JsonTrackStatistics', 'KeyValuePairOfInt32AndDownloadProgress', 'LastFmStatistics', 'LastFmTag', 'LibraryCacheTrackStatus', 'LibraryReleaseDownloadStatusUpdate', 'ListenBrainzQueryRoot', 'MbAlbumImages', 'MbArtistImages', 'MbLabelInfo', 'MbMedium', 'MbNameCredit', 'MbRelation', 'MusicBrainzArtistSearchRoot', 'MusicBrainzRecordingSearchRoot', 'MusicBrainzReleaseGroupSearchRoot', 'MusicBrainzReleaseSearchRoot', 'MusicBrainzSearchRoot', 'OnlineClient', 'PageInfo', 'PlaylistSearchRoot', 'RecommendationsSearchRoot', 'ReleaseServiceConnections', 'ScoredRelease', 'ServerLibrarySearchRoot', 'SharingStatistics', 'SimilarArtist', 'SlotProgressUpdate', 'SlotStatusUpdate', 'SpotifyArtistSearchRoot', 'SpotifyImage', 'SpotifyPlaylistSearchRoot', 'StorageStats', 'TrackCredit', 'TrackStatistics', 'UserSearchRoot', 'UsersConnection', 'UsersEdge'];
  return typesWithNoId.includes(type);
}
