import { KeyGenerator } from "@urql/exchange-graphcache";
import { TypesWithNoId } from "@/gql/types-with-no-id.ts";

export const cacheKeys: Record<TypesWithNoId, KeyGenerator> = {
  ArtistSearchRoot: () => null,
  DownloadsSearchRoot: () => null,
  ImportPlaylistSearchRoot: () => null,
  LastFmStatistics: () => null,
  LastFmTag: () => null,
  MbAlbumImages: () => null,
  MbArtistImages: () => null,
  MbMedium: () => null,
  MbNameCredit: () => null,
  MbRelation: () => null,
  MusicBrainzArtistSearchRoot: () => null,
  MusicBrainzRecordingSearchRoot: () => null,
  MusicBrainzReleaseGroupSearchRoot: () => null,
  MusicBrainzReleaseSearchRoot: () => null,
  MusicBrainzSearchRoot: () => null,
  NameCredit: () => null,
  PageInfo: () => null,
  PlaylistSearchRoot: () => null,
  RecommendationsSearchRoot: () => null,
  ReleaseGroupSearchRoot: () => null,
  ReleaseSearchRoot: () => null,
  SpotifyPlaylistSearchRoot: () => null,
  UserProjection: () => null,
  UserSearchRoot: () => null,
  UsersConnection: () => null,
  UsersEdge: () => null,
};
